### ISSUE TITLE
mintAsset requires mint Metadata

### ISSUE THREAD

**Issue by nielstron** [MeshJS/mesh#100]
The examples only show minting with Metadata attached and trying to omit it when building a mintAsset transaction fails. Metadata should however not be a _requirement_ for minting assets.

**Comment by eric248550** [comment]
Hello, is there an alternative solution for this?

> The examples only show minting with Metadata attached and trying to omit it when building a mintAsset transaction fails. Metadata should however not be a _requirement_ for minting assets.
