### ISSUE TITLE
Yoroi not detected

### ISSUE THREAD

**Issue by magick93** [MeshJS/mesh#101]
Hello

What wallets are detected?

I have Yoroi and Yoroi Nightly installed, yet when I go to https://meshjs.dev/apis/browserwallet neither are detected.

**Comment by Gns7077DEV** [comment]
@magick93 Talk to Cardano  Support on the [Cardano Live Support](https://explore-cardano.org/) so that your issue can be looked into.

**Comment by magick93** [comment]
Hi @Gns7077DEV - isnt the issue due to this PR not being merged - https://github.com/MeshJS/mesh/pull/48 ?

**Comment by Gns7077DEV** [comment]
You should create chat with the support sent to you for more knowledge and procedures to solve the issue .

**Comment by magick93** [comment]
@jinglescode - please see above. This guy is trying to promote a scam site.

**Comment by Gns7077DEV** [comment]
what do you mean?

**Comment by Gns7077DEV** [comment]
are you a kid or how old are you?

**Comment by jinglescode** [comment]
Hey @magick93, thanks for reporting. For Yorio, I am not detecting it either. But I would like you to do something and confirm with me.
1. open a browser tab, with that browse that has Yoroi installed
2. right click and `inspect element`
3. go to `Console` tab
4. type `window.cardano`
5. see what wallets are "found"

**Comment by magick93** [comment]
HI @jinglescode 

This is what I get:

![image](https://user-images.githubusercontent.com/2173213/221742376-4f872f78-c8a7-4b09-be99-8164b0bac028.png)

**Comment by magick93** [comment]
@jinglescode - is the problem that yoroi is missing from this list? https://github.com/MeshJS/mesh/blob/main/packages/module/src/common/constants.ts#L481-L483

**Comment by jinglescode** [comment]
@magick93. Your screenshot is good, this means`yoroi` is on your device. And yes, we just have to add `yoroi` into `SUPPORTED_WALLETS`.

**Comment by magick93** [comment]
Thanks @jinglescode - I've added a PR - https://github.com/MeshJS/mesh/pull/105

**Comment by abdelkrimdev** [comment]
Hi, @magick93 unfortunately Yoroi doesn't fully support the CIP-30 specs.
Adding `yoroi` to the array of supported wallets isn't enough 😅 
we have to make changes to the BrowserWallet class too
