### ISSUE TITLE
Svelte

### ISSUE THREAD

**Issue by magick93** [MeshJS/mesh#104]
Hello

I'm interested in using MeshJs in a new project. However the project is based on Svelte, rather than React.

Do I just use the `@meshsdk/core` package? Does this have all the functionality, minus the presentation layer?

Thanks

**Comment by abdelkrimdev** [comment]
Yes it should work just fine as long as you use `webpack` instead of `Vite` as a bundler
`@meshsdk/core` doesn't depend on or use `React` at all you can use it with any framework even in a `Node.js` application.
