### ISSUE TITLE
resolveSlotNo returns incorrect POSIX TIme 

### ISSUE THREAD

**Issue by safi-ullah08** [MeshJS/mesh#118]
Here is an example of how I am using it 
```

const addMinutes = (minutes) => {
  return new Date(Date.now() + minutes * 60000).getTime();
};

const slot = resolveSlotNo('preprod', addMinutes(10));

```

`slot = 27345986`

When I use this deadline in my validator  I get the following error

`{"invalidBefore":27345986,"invalidHereafter":null},"currentSlot":25198745}`

This seems to be way off, I believe its not the addMinutes functions because I have tried it and it returns a valid timestamp

**Comment by HinsonSIDAN** [comment]
Fixed with some test case provided at - https://github.com/MeshJS/mesh/blob/main/packages/mesh-common/test/data/time.test.ts
