### ISSUE TITLE
blockfrostProvider.fetchAssetAddresses is not a function

### ISSUE THREAD

**Issue by v0d1ch** [MeshJS/mesh#119]
The title says it all. I tried using the blockfrost provider but it seems the `fetchAssetAddresses` is not available.

Relevant piece of code is taken from one of your examples but I'll paste it here just for the reference:
```
    const blockfrostProvider = new BlockfrostProvider('*************');
    let x = await blockfrostProvider.fetchAssetAddresses(
      'd9312da562da182b02322fd8acb536f37eb9d29fba7c49dc172555274d657368546f6b656e',
    )

    console.log(x);

```

Am I doing something wrong here? (sorry not a frontend guy)

**Comment by jinglescode** [comment]
I tried the [demo](https://meshjs.dev/providers/blockfrost#fetchAssetAddresses), its fine.

From your code snippet, it looks ok. 

Maybe you need to put inside a `async` function? Its really difficult to tell what the problem is from your code snippet.

**Comment by v0d1ch** [comment]
@jinglescode The rest of the `blockfrost` examples work for me but this particular one does not (fails with the message in the issue title). [Here](https://github.com/v0d1ch/hydra-explorer/blob/fetchAssetAddresses/hydra-explorer/pages/index.tsx) is a link to the file so you can take a peek.

**Comment by jinglescode** [comment]
you missed the word `await`? See https://meshjs.dev/providers/blockfrost#fetchAssetAddresses

```
let heads = await blockfrostProvider.fetchAssetAddresses(
          'd9312da562da182b02322fd8acb536f37eb9d29fba7c49dc172555274d657368546f6b656e',
         )
```

**Comment by v0d1ch** [comment]
@jinglescode turns out I was on version `1.5.0` :facepalm:
