### ISSUE TITLE
Send lovelace/ADA to legacy Byron address

### ISSUE THREAD

**Issue by iKoala** [MeshJS/mesh#128]
Hi, I have a question about sending ADA to legacy Byron address.
I tried to call .sendLovelace with Byron Icarus address recipient but it failed with `mixed-case strings not allowed` error, 
may I know if MeshJS Transaction supports Byron address?
I am sorry if this problems has been stated in the MeshJS docs but I tried to search for the error and information and have no luck with it.
Thanks in advance!

**Comment by abdelkrimdev** [comment]
MeshJS doesn't support Byron era addresses
