### ISSUE TITLE
Support metadata with conversions 

### ISSUE THREAD

**Issue by thuyvu17** [MeshJS/mesh#135]
The current implementation of the setMetadata function does not support any JSON schema conversions for metadata.
```
setMetadata(key: number, value: unknown): Transaction {
    this._txBuilder.add_json_metadatum_with_schema(
      csl.BigNum.from_str(key.toString()), JSON.stringify(value),
      csl.MetadataJsonSchema.NoConversions,
    );

    return this;
  }
```
However, the `cardano-serialization-lib` provides two additional `MetadataJsonSchema` options, namely `BasicConversions` and `DetailedSchema`. These conversions play a vital role and are essential in the context of metadata handling.

**Comment by HinsonSIDAN** [comment]
This is fixed right now probably, please re-open if issue persist
