### ISSUE TITLE
Why my lace wallet is Not Detect.

### ISSUE THREAD

**Issue by nguyenvuhoang** [MeshJS/mesh#142]
I have installed Lace wallet on browser. I have open home page of Mesh. Wallet List have see Lace. But my app have using ConnectWallet component don't see Lace on WalletList

**Comment by jinglescode** [comment]
some suggestions:
- update to the latest version
- from your app, check using `BrowserWallet`
- build your own wallet UI component

**Comment by nguyenvuhoang** [comment]
I have updated new version. It worked.. Thanks. 

How about Yoroi

**Comment by ernst223** [comment]
@nguyenvuhoang to what version did you updated to? I am running 1.5.2 and getting this problem. Using the BrowserWallet.getInstalledWallets(); 
Can't see my lace or yoroi wallet
