### ISSUE TITLE
Can't resolve '@meshsdk/core'

### ISSUE THREAD

**Issue by dmetree** [MeshJS/mesh#155]
Got this error right after: 
$npm install @meshsdk/react
and
import { MeshProvider } from "@meshsdk/react";

ERROR in ./node_modules/@meshsdk/react/dist/react.js 2:0-71
Module not found: Error: Can't resolve '@meshsdk/core' in ...\node_modules\@meshsdk\react\dist'

**Comment by SIDANWhatever** [comment]
Can you provide more details in reproducing the issue? e.g. the github repo for source code.

**Comment by dmetree** [comment]
Resolved it, the issue was using React not Next.js. With Next.js everything works fine.

**Comment by ojonah** [comment]
I'm having a similar error in a React project.  How did your resolve the error? Thanks,
ERROR in /node_modules/@emurgo/cardano-message-signing-browser/cardano_message_signing_bg.js Can't import the named export wbindgen_malloc' (imported as 'wasm') from default-exporting module (only default export is available)
