### ISSUE TITLE
AppWallet: incapable of sending assets from wallet

### ISSUE THREAD

**Issue by BenElferink** [MeshJS/mesh#156]
I generated a new mnemonic using AppWallet.
I then loaded that wallet with NFTs and ADA.

I am able to send ADA from the wallet, but I am incapable of sending any NFT from the wallet, I always get the error:
```
[Transaction] An error occurred during build: Not enough ADA leftover to include non-ADA assets in a change address.
```

The wallet has 168 NFTs, and 470+ ADA, this should be enough, right?
Is there a limit to the number of NFTs an AppWallet can handle?

I had to import the wallet into a browser extension and manually send out my NFTs.

**Comment by jinglescode** [comment]
There is no limit to the number of NFTs any wallet can handle unless limited by the network's specs, i.e. transactions size limits.

You have to build the transactions correctly, providing enough + correct inputs.
