### ISSUE TITLE
Lace Wallet wallet signature not generating properly

### ISSUE THREAD

**Issue by kamranhafeezbim** [MeshJS/mesh#158]
Hi, hope you are doing well
I have a DAPP that uses lace wallet and the whole flow is that first user connects the wallets and after successful connection the message signing method is called, but the wallet signature is generated after some time and on first attempt it generates an invalid signature upon second request it generates the correct signature and in both cases it takes time. Can anyone tell me why is this happening, I also have tried updating my version still no luck

**Comment by abdelkrimdev** [comment]
Mesh is asking the wallet for signature then it adds it to the transaction witnesses. I suggest you try to call the sign function directly and see if it is still behaving the same
