### ISSUE TITLE
Typhon Wallet not supported yet

### ISSUE THREAD

**Issue by belferink1996** [MeshJS/mesh#17]
Typhon Wallet is a CIP-30 wallet developed by Cardanoscan.io
I use this wallet, and it's not detected by Mesh yet, please add support for it

**Comment by abdelkrimdev** [comment]
Hi @belferink1996 😀
Yep, it will be added on `1.2.0` alongside other exciting features 😉

**Comment by gerciljunio** [comment]
will you also add gerowallet? Any idea when this new version will come out? I want to use mesh in my projects!

**Comment by belferink1996** [comment]
> Hi @belferink1996 😀 Yep, it will be added on `1.2.0` alongside other exciting features 😉

I see `1.2.0` is released, and yet Typhon is still not supported?

**Comment by abdelkrimdev** [comment]
Hi @belferink1996, please make sure to use version `1.2.1` or higher.

**Comment by belferink1996** [comment]
Gotcha, I was checking for a new release every day using NCU.
I didn't realize new releases were put out under a different package name.

I had `@martifylabs/mesh` installed, it seems that's change to `@meshsdk/core` & `@meshsdk/react`.
Now I have the latest release and Typhon is detected.
