### ISSUE TITLE
When using connect(walletName) in React with useWallet(), errors go to console but the promise resolves regardless

### ISSUE THREAD

**Issue by esot321c** [MeshJS/mesh#174]
One example error which I'd like to be able to catch and show the user: 
```
Error: [BrowserWallet] An error occurred during enable: Error: no account set.
    at Ft.enable (core.js:2955:1)
    at async eval (react.js:1320:1)
```
This is an issue with Eternl but it's impossible to give the user any hints about fixing it because the error skips any try/catch block logic, or promise resolve.

**Comment by jinglescode** [comment]
```
const { wallet, connected, name, connecting, connect, disconnect, error } = useWallet();
```

listening to the `error` in `useWallet();` will return the error as you have shown.
