### ISSUE TITLE
useAssets() Asset type doesn't include all the properties. 

### ISSUE THREAD

**Issue by esot321c** [MeshJS/mesh#176]
when using useAssets in meshsdk/react, the Asset type doesn't include all the properties. The given type: 

```
export declare type Asset = {
    unit: Unit;
    quantity: Quantity;
};
```
But the actual repsonse is typed like this: 
```
{
    "unit": string;
    "policyId": string;
    "assetName": string;
    "fingerprint": string;
    "quantity": string;
  }
  ```

**Comment by abdelkrimdev** [comment]
properties such as `policyId`, `assetName` and, `fingerprint` can be infred from `unit`
