### ISSUE TITLE
Error: ENOENT: no such file or directory, open '...\.next\server\chunks\cardano_serialization_lib_bg.wasm'

### ISSUE THREAD

**Issue by nguyenvuhoang** [MeshJS/mesh#183]
Dear All

       When we're build the application, but it show one message "**Error: ENOENT: no such file or directory, open '...\.next\server\chunks\cardano_serialization_lib_bg.wasm**'"

Could you help me

**Comment by nguyenvuhoang** [comment]
Hello Everyone

**Comment by atrhacker** [comment]
Same issue here.
In my case it's not working withtt the latest version from next.js (14.0.4) and the app router.

**Comment by nguyenvuhoang** [comment]
Actually, i have read this https://github.com/vercel/next.js/issues/55537 but i see it seem error from version of Webpack 5 isn't detecting correctly the wasm dependency.

Do you have any recommend for this case?

**Comment by chrissiwaffler** [comment]
@nguyenvuhoang are you using the app directory (a feature introduced with next 13)?

**Comment by nguyenvuhoang** [comment]
> @nguyenvuhoang are you using the app directory (a feature introduced with next 13)?

Yes we're using App Directory (Upgrade to Next 14)

**Comment by chrissiwaffler** [comment]
@nguyenvuhoang 
if the error still occurs at your end, you might want to look into my this answer: https://github.com/MeshJS/mesh/pull/152#issuecomment-1708656146
It's a workaround which solved my own issue, and might help you as well.

**Comment by matejfalat** [comment]
Got the same error (Next 14, app router), but using `next/dynamic` to import components seems to help. E.g.:

```
import dynamic from 'next/dynamic'

const MeshProvider = dynamic(
  () => import('@meshsdk/react').then((mod) => mod.MeshProvider),
  {ssr: false},
)
```

**Comment by HinsonSIDAN** [comment]
Packaging has been refactored entirely since version V1.6, please re-open if issue persists
