### ISSUE TITLE
Multiple vulnerabilities in example templates

### ISSUE THREAD

**Issue by B3nac** [MeshJS/mesh#191]
Just so everyone is aware there are some outdated and deprecated dependencies in the examples.

```
added 320 packages, and audited 321 packages in 27s

85 packages are looking for funding
  run `npm fund` for details

11 vulnerabilities (1 low, 8 moderate, 1 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix
```

Any plans to update the templates? After running npm audit there are 12 Medium severity vulnerabilities.

**Comment by HinsonSIDAN** [comment]
We have performed repackage. Please re-open the issue if that persists.
