### ISSUE TITLE
React + MeshJS error when using `import { MeshProvider } from '@meshsdk/react';` after manual install via webpack

### ISSUE THREAD

**Issue by ojonah** [MeshJS/mesh#192]
ERROR in ./node_modules/@emurgo/cardano-message-signing-browser/cardano_message_signing_bg.js 
Can't import the named export '__wbindgen_realloc' (imported as 'wasm') from default-exporting module (only default export is available)

webpack compiled with 448 errors and 2 warnings

The error is above, for background I'm trying to use Mesh in a React project.  I followed the manual installation using the webpack option. and have added the webpack.config.cjs  code into the existing webpack.config.js I found in the project.  I'm getting the error anytime i try to use import with @meshsdk.  Like import { MeshProvider } from '@meshsdk/react';

I'm certain I've done something wrong, any guidance would help.

**Comment by chrissiwaffler** [comment]
do you happen to use Next.js? @ojonah

**Comment by ojonah** [comment]
No, I have not used Next.js before. Is that required?

**Comment by chrissiwaffler** [comment]
no, @ojonah it's not required.

So you're just using React with webpack 5, right?

**Comment by ojonah** [comment]
Yes, just React but I'm not sure on the webpack version. is there a way to check this?

**Comment by ojonah** [comment]
In my package.json its showing webpack 5.90.3

**Comment by ojonah** [comment]
I'm suspecting the error message I'm encountering suggests that there's an issue with the way the @emurgo/cardano-message-signing-browser package is being imported. How can I check the webpack configuration to ensure that the webpack configuration is set up correctly to handle the imports from @emurgo/cardano-message-signing-browser, and to make sure that I'm using the appropriate loader for WebAssembly modules. @chrissiwaffler

**Comment by abdelkrimdev** [comment]
Hi @ojonah, have you tried to add
```
 experiments: {
    asyncWebAssembly: true,
  }
```
to your webpack config?

**Comment by JaniPrasant** [comment]
@ojonah I'm having the same issue, did you find solution for the same?

**Comment by nguyenvuhoang** [comment]
Check #183

**Comment by nguyenvuhoang** [comment]
if the error still occurs at your end, you might want to look into my this answer: https://github.com/MeshJS/mesh/pull/152#issuecomment-1708656146

**Comment by HinsonSIDAN** [comment]
Packaging has been refactored entirely since version V1.6, please re-open if issue persists
