### ISSUE TITLE
Memory access out of bounds

### ISSUE THREAD

**Issue by gammahazard** [MeshJS/mesh#196]
hey I was trying to use webpack to bundle meshjs and use it so it can be imported into an html page, the browser wallet object is imported fine and I can connect to different wallets, but when I try to build a transaction I get the error RuntimeError: memory access out of bounds
<img width="240" alt="ee9ce0ccc9281f3bf70f847a0eaddfd6" src="https://github.com/MeshJS/mesh/assets/92896466/12717422-9c43-4f3d-ae07-3ebe6bbcbe92">

I was running a simple express server and rendering the html on that for testing

**Comment by WolfRayet4** [comment]
Not sure if this is the same issue I encountered - but I found this error occur when you pass the quantity as an integer rather than a string. It needs to be a string (of the number)

**Comment by jinglescode** [comment]
> Not sure if this is the same issue I encountered - but I found this error occur when you pass the quantity as an integer rather than a string. It needs to be a string (of the number)

@gammahazard this could be the case, in order to prevent rounding errors, we made a design choice to use strings for numbers. Quantity needs to be strings.
