### ISSUE TITLE
Lower level API - Adding meaningful error at build

### ISSUE THREAD

**Issue by HinsonSIDAN** [MeshJS/mesh#210]
Input guard:
- [ ] script supplied doesnt equal spending key of address / policy
- [ ] To add

Complete guard:
- [ ] return the tx evaluation error
- [ ] To add

Others:
- [ ] raw script vs double cbor encoding

**Comment by SIDANWhatever** [comment]
@workshop-maybe can add on the list here if you got any recommendation
