### ISSUE TITLE
StakeButton UI component stuck in "checking" status

### ISSUE THREAD

**Issue by Fuma419** [MeshJS/mesh#254]
<img width="1632" alt="Screenshot 2024-08-08 at 9 52 16 AM" src="https://github.com/user-attachments/assets/483b52a6-7fd9-4846-bf68-622f609b9fa9">

https://meshjs.dev/react/ui-components#stakeButton

I have been using this UI component but the recent update from 1.1.10-beta.3 to 1.6.2 has broken this StakeButton component. I am seeing the same issue on your demo implementation mentioned above.

**Comment by jinglescode** [comment]
hey @Fuma419 im not sure how to reproduce this problem you have reported.
could you provide info about your wallet?

**Comment by jinglescode** [comment]
@Fuma419 recommend to build your own tx using [txbuilder](https://meshjs.dev/apis/txbuilder/staking)
