### ISSUE TITLE
Cannot read properties of undefined (reading 'PrivateKey') using Vite (Vue3/Nuxt)

### ISSUE THREAD

**Issue by PalmerEk** [MeshJS/mesh#257]
Receive the error 

> Cannot read properties of undefined (reading 'PrivateKey')

when including Mesh in Vue 3 / Nuxt based projects.  

Appears to be an issue with importing @stricahq/* (and @emurgo/cip14-js)

**Comment by NanezX** [comment]
Same issue here. My project used the ^1.5.4 and then this allow to be resolved to 1.6.4 and crashed with this error. The whole app crashed so I had to fix the version to 1.5.4

**Comment by jinglescode** [comment]
working on it

**Comment by tabdon** [comment]
@PalmerEk would you mind sharing your vite.config.js? I had a vite project that was working, and then suddenly it stopped. I'm getting the same errors you are. I've downgraded to old versions and it's still happening. I'm puzzled.

**Comment by jinglescode** [comment]
@PalmerEk @NanezX @tabdon try version `1.6.5`

**Comment by tabdon** [comment]
@jinglescode so far so good! thanks!
