### ISSUE TITLE
Transaction address cut short

### ISSUE THREAD

**Issue by bigbenbeer** [MeshJS/mesh#26]
## Problem
Whenever I run `...getPaymentAddress()` it returns only 58 characters of the payment address. For example, one of my wallet addresses it returns is: `addr1vyjpy2h4s9zk975vcvfe6g7v5qmrfnc4f7s6zmrg022wf3s3qfda4` where the actual is supposed to be `addr1qyjpy2h4s9zk975vcvfe6g7v5qmrfnc4f7s6zmrg022wf35kssj30r270nm07q3sz7gsquygkhsqxdfkxz6wcuwvc2fsvj99ks`

**Comment by abdelkrimdev** [comment]
Hey @bigbenbeer 😄 
AppWallet gives you the payment address without staking capabilities that's why it is shorter.

Cardano has three types of addresses:
- Payment Address aka Enterprise
- Stake Address aka Stake Key
- BaseAddress is a combination of the previous two

**Comment by bigbenbeer** [comment]
> Hey @bigbenbeer 😄 AppWallet gives you the payment address without staking capabilities that's why it is shorter.
> 
> Cardano has three types of addresses:
> 
>     * Payment Address aka Enterprise
> 
>     * Stake Address aka Stake Key
> 
>     * BaseAddress is a combination of the previous two

Ah, I see; I would suggest just adding that calrification somewhere in the docs for people to see as well. 

Is it possible to get the Base address using Mesh?

**Comment by abdelkrimdev** [comment]
> Is it possible to get the Base address using Mesh?
You can't do that at the moment, but we can implement it if you think it should be there 😄

**Comment by ihor-repela** [comment]
@abdelkrimdev 
It would be really nice to have this feature
