### ISSUE TITLE
unable to build tx on nextjs app 

### ISSUE THREAD

**Issue by gammahazard** [MeshJS/mesh#270]
hey, was running into some issues, can't seem to get my transaction built on my nextjs app, wallet connection and everything else works fine, but when trying to send the tx to build it returns: `ada.js:85  Failed to send ADA transaction: Error
    at CSLSerializer.serializeTxBody (index.js:943:1)
    at MeshTxBuilder.complete (index.js:1298:1)
console.error @ client.js:1
window.console.error @ setup-hydration-warning.js:18
sendAdaTransaction @ ada.js:85
await in sendAdaTransaction
handleSendWithWallet @ AddressDisplay.js:56
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
eval @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26179
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430
Show 17 more frames
Show less
ada.js:86  Error details: 
console.error @ client.js:1
window.console.error @ setup-hydration-warning.js:18
sendAdaTransaction @ ada.js:86
await in sendAdaTransaction
handleSendWithWallet @ AddressDisplay.js:56
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
eval @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26179
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430
Show 17 more frames
Show less
ada.js:88  Error stack: Error
    at CSLSerializer.serializeTxBody (webpack-internal:///./node_modules/@meshsdk/core-csl/dist/index.js:1036:13)
    at MeshTxBuilder.complete (webpack-internal:///./node_modules/@meshsdk/transaction/dist/index.js:1307:33)` was using asyncwebassembly in my config as well , any ideas

**Comment by cmorgado** [comment]
Please check if your wallet has colateral set.
II was having the same issue and found out this to be the cause.

**Comment by gammahazard** [comment]
I had tried setting collateral was still seeing the same issue , will try to play around today and see if I can figure it out !

**Comment by BenElferink** [comment]
What wallet are you using? `BrowserWallet` or `AppWallet`?
I use `AppWallet`, and cannot build TXs either (I was able to on older versions of Mesh).
Here's [my issue](https://github.com/MeshJS/mesh/issues/246#issuecomment-2307625581)
