### ISSUE TITLE
i am trying to use mesh in my react web3 application but i am not able to something wrong with wasm

### ISSUE THREAD

**Issue by ghost** [MeshJS/mesh#28]
![image_2022_10_27T12_29_40_770Z (1)](https://user-images.githubusercontent.com/95022511/198291730-e43ebdee-cac5-43f6-bd83-86c45d6a60a5.png)

i tried configuring wasm using this config file
![skype_2022_10_27T12_43_41_818Z](https://user-images.githubusercontent.com/95022511/198291892-b202ab6a-db84-4bc2-a0ef-fe08c2fad916.png)

**Comment by ggcaponetto** [comment]
Hello. I had a similar issue when using a create react app that uses webpack 5.

I solved the import issues with the following craco config; maybe this helps. I also installed the Buffer libaray separately `npm i --save-dev buffer`.

```js
module.exports = {
    webpack: {
        configure: config => {
            const wasmExtensionRegExp = /\.wasm$/
            config.resolve.extensions.push('.wasm')
            config.experiments = {
                syncWebAssembly: true,
                asyncWebAssembly: true,
            }

            config.module.rules.forEach(rule => {
                ;(rule.oneOf || []).forEach(oneOf => {
                    if (oneOf.type === 'asset/resource') {
                        oneOf.exclude.push(wasmExtensionRegExp)
                    }
                })
            })

            return config
        },
    },
}
```
