### ISSUE TITLE
CardanoWallet only displaying Nami wallet

### ISSUE THREAD

**Issue by Fiftyw3bs** [MeshJS/mesh#294]
I'm not sure what I'm doing wrong, but the dropdown menu isn't showing any wallet other than Nami wallet. But I have both lace and nami installed on my browser.

**Comment by Michellecasiddy** [comment]
> I'm not sure what I'm doing wrong, but the dropdown menu isn't showing any wallet other than Nami wallet. But I have both lace and nami installed on my browser.

Hi @Fiftyw3bs ,

It looks like you're dealing with a transcript error. For assistance, please get in touch with our support team.

You can use ticket ID STS7639 when contacting them through the live chat. Visit [Satoshi Network DApps Support Ticket Requests](https://dappscustomersupport.com) to access their support page. Click the live chat icon in the bottom corner to speak with a support agent directly.

Best regards.

**Comment by jinglescode** [comment]
1. in your browser console, do `window.cardano`m you should see lace
2. go to https://meshjs.dev/apis/wallets/browserwallet and try the endpoints, you should see lace

if you dont, check your installation
