### ISSUE TITLE
Transactions with plutus script

### ISSUE THREAD

**Issue by jinglescode** [MeshJS/mesh#315]
- https://meshjs.dev/apis/txbuilder/smart-contract
- [ ] `txOutInlineDatumValue`
- [ ] `txInScript`
- [ ] `txInRedeemerValue`
- [ ] `txInInlineDatumPresent`
- [ ] plutus minting `mintingScript`
- [ ] `mintRedeemerValue`
- [ ] `mintPlutusScriptV2`
- [ ] `txOutReferenceScript`

**Comment by twwu123** [comment]
Currently mostly working, however, there are some bugs after evaluation, script integrity checks fail.

**Comment by twwu123** [comment]
Done
