### ISSUE TITLE
setFees()

### ISSUE THREAD

**Issue by jinglescode** [MeshJS/mesh#351]
Need to be able to set the ADA fee manually, where its needed to enable sponsored transactions, babel fees and schedule transactions on Cardano.

**Comment by Tao546127REP** [comment]
> Need to be able to set the ADA fee manually, where its needed to enable sponsored transactions, babel fees and schedule transactions on Cardano.


Hey @jinglescode Gotcha! Being able to set the ADA fee manually would definitely help with enabling sponsored transactions and managing fees better on Cardano. It seems like a feature that could really enhance user experience, especially for those who want more control. Hopefully, the team will consider adding that functionality in future updates! Keep an eye out for any announcements!

**Comment by jinglescode** [comment]
done https://meshjs.dev/apis/txbuilder/basics#setFee
