### ISSUE TITLE
Named export 'Bip32PublicKey' not found. The requested module '@stricahq/bip32ed25519' is a CommonJS module, which may not support all module.exports as named exports.

### ISSUE THREAD

**Issue by JustLeif** [MeshJS/mesh#392]
### Summary

I actually might have introduced this by accident with a previous PR:
https://github.com/MeshJS/mesh/commit/6b2682462475073102d964a0600770cf30e5189c

I think the solution would be to use this wrapper import for the Bip32PublicKey class instead of importing directly from the commonjs module.
<img width="1192" alt="Screenshot 2024-11-17 at 20 12 03" src="https://github.com/user-attachments/assets/77a54d2d-7123-419d-96c8-54f06ae49c5d">

If that is in fact the issue: this PR will fix it. https://github.com/MeshJS/mesh/pull/393

But you probably know better at why I'm experiencing this issue.

### Actual Result

<img width="1200" alt="Screenshot 2024-11-17 at 20 07 18" src="https://github.com/user-attachments/assets/6521391b-93a6-4762-a496-9dbc175e9dd3">

### Expected Result

Being able to import the MeshSDK without an error.

### SDK version

1.7.16

### Environment type

- [X] Node.js
- [ ] Browser
- [ ] Browser Extension
- [ ] Other

### Environment details

Node.js 22.

**Comment by jinglescode** [comment]
try version `1.7.17`

**Comment by JustLeif** [comment]
> try version `1.7.17`

Okay it's working for me now. Thanks for fixing it! 👍
