### ISSUE TITLE
Error submitting transaction.

### ISSUE THREAD

**Issue by independenceee** [MeshJS/mesh#398]
### Summary

I encountered an error while submitting the transaction.

### Steps to reproduce the bug

![image](https://github.com/user-attachments/assets/dc901991-1b3f-4f8a-baf8-73d01c3e47e1)

### Actual Result

error: {"data":{"error":"Bad Request","message":"{\"contents\":{\"contents\":{\"contents\":{\"era\":\"ShelleyBasedEraConway\",\"error\":[\"ConwayUtxowFailure (PPViewHashesDontMatch (SJust (SafeHash \\\"5db5584695fc312bf28a5318db7742066905ce25d306fe5e0b32e9c7f95e717c\\\")) (SJust (SafeHash \\\"46e1d77f8f5ecd25394d3574261b226e05ae00843d36c2f37fabb322ef198f82\\\")))\"],\"kind\":\"ShelleyTxValidationError\"},\"tag\":\"TxValidationErrorInCardanoMode\"},\"tag\":\"TxCmdTxSubmitValidationError\"},\"tag\":\"TxSubmitFail\"}","status_code":400},"headers":{"date":"Mon, 18 Nov 2024 05:55:21 GMT","content-type":"application/json; charset=utf-8","content-length":"524","connection":"keep-alive","vary":"Origin","access-control-allow-origin":"*","report-to":"{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=FgjnnKYDgQ8I9Y8jceWyqxefYO0%2FGmvopBJ3VG3fYOTyTKIyJHyyLcY3gDrEG7YRUVMwJF%2BYZWOQA8KvzG3II1%2F18Jr0ESGrV9DORR8vu99f1WNNuDibJQ3MBQvCgiy1c4hN6nBSuuK9xeziYI14\"}],\"group\":\"cf-nel\",\"max_age\":604800}","server-timing":"cfL4;desc=\"?proto=TCP&rtt=48651&sent=8&recv=9&lost=0&retrans=0&sent_bytes=4270&recv_bytes=3459&delivery_rate=90490&cwnd=122&unsent_bytes=0&cid=7b2b9df8e9415e0f&ts=1189&x=0\"","bf-submit-server":"e1f4ccc29ee5a9bb1f2d55e35e58119727c3f3f0e0da9c0cf0a9582299058083","cf-cache-status":"DYNAMIC","nel":"{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}","server":"cloudflare","cf-ray":"8e45b6041d7e1065-HKG"},"status":400}

### Expected Result

txHash

### SDK version

1.7.13

### Environment type

- [X] Node.js
- [ ] Browser
- [ ] Browser Extension
- [ ] Other

**Comment by jinglescode** [comment]
1. update to latest version
2. `setNetwork('preprod')` https://meshjs.dev/apis/txbuilder/basics#setNetwork
