### ISSUE TITLE
mesh cli, setup does not install all dependencies

### ISSUE THREAD

**Issue by jinglescode** [MeshJS/mesh#425]
### Summary

problem: when using CLI, the setup doesnt install every packages.

```
Module not found: Can't resolve '@harmoniclabs/pair'
  24 | var bigint_utils_1 = require("@harmoniclabs/bigint-utils");
  25 | var plutus_data_1 = require("@harmoniclabs/plutus-data");
> 26 | var pair_1 = require("@harmoniclabs/pair");
     | ^
  27 | var UPLCTermTag_1 = require("../UPLCTerm/UPLCTermTag.js");
  28 | var Constr_1 = require("../UPLCTerms/Constr.js");
  29 | var Case_1 = require("../UPLCTerms/Case.js");

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@harmoniclabs/uplc/dist/index.js
./node_modules/@meshsdk/core-cst/dist/index.js
./node_modules/@meshsdk/wallet/dist/index.js
./node_modules/@meshsdk/react/dist/index.js
./src/pages/_app.tsx
```

the [template](https://github.com/MeshJS/mesh-nextjs-template) is working fine, as manually clone this repo, `npm install` and `npm run dev` will work.

### Steps to reproduce the bug

1. from terminal, do `npx meshjs test-app`, choose `nextjs`
2. then start `npm run dev`

you will see error about `hlab/pair` not found, and indeed from node_modules the package was not installed

3. then do `npm install`
4. then start `npm run dev` again

you will see the everything running fine.

### Actual Result

error `hlab/pair` is not found, after doing `npx meshjs test-app`

### Expected Result

from terminal, do `npx meshjs test-app` should set everything up ready for development.

CLI script can be found here [scripts/mesh-cli/src/index.ts](https://github.com/MeshJS/mesh/tree/main/scripts/mesh-cli)

**Comment by HinsonSIDAN** [comment]
I can reproduce this with `yarn` package manager. Indeed no matters how many times i run `yarn install`, it is still reporting same error. A quick fix is maybe enforcing npm as default?

**Comment by lisicky** [comment]
Just FYI @jinglescode @HinsonSIDAN , yarn doesn’t install peer dependencies. But you can try to reinstall hlab packages with install-peerdeps tool

**Comment by jinglescode** [comment]
> Just FYI @jinglescode @HinsonSIDAN , yarn doesn’t install peer dependencies. But you can try to reinstall hlab packages with install-peerdeps tool

currently, have [hardcoded to use `npm`](https://github.com/MeshJS/mesh/blob/main/scripts/mesh-cli/src/helpers/resolvePkgManager.ts)

do you think can improve this [script](https://github.com/MeshJS/mesh/tree/main/scripts/mesh-cli/src) to support yarn?
