### ISSUE TITLE
checkSignature is not working on nextjs app router

### ISSUE THREAD

**Issue by mackieq** [MeshJS/mesh#443]
### Summary

I use checkSignature from '@meshsdk/core', and I followed thsi doc:  https://meshjs.dev/guides/prove-wallet-ownership
First, I use pages/api/verify-sign, It works.

But when I use the app router, I moved the code to app/api/verify-sign/route.ts. I debug step by step, and when I add 
`const isValid = checkSignature(nonce, signature, address), `
the entire API returns a 404 with no output. However, when I remove that checkSignature line, the API returns normally, and the logs are printed. In my console, I can see the warning:

```
 Import trace for requested module: 
./node_modules/@sidan-lab/sidan-csl-rs-nodejs/sidan_csl_rs.js ./node_modules/@meshsdk/core-csl/dist/index.js
./node_modules/@meshsdk/core/dist/index.js 
./src/app/api/verify-sign/route.ts"
```

my next config file :

`import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactStrictMode: true,
  webpack: function (config, {isServer}) {
    config.experiments = {
      asyncWebAssembly: true,
      layers: true,
    };
    if (!isServer) config.target = "web"
    return config;
  },
  async rewrites() {
    return [
      {
        source: '/cgent/:path*', 
        destination: 'http://localhost:8080/cgent/:path*', 
      },
    ];
  }
};

export default nextConfig;
`

### Actual Result

no

### Expected Result

no

### SDK version

1.8.0

### Environment type

- [X] Node.js
- [X] Browser
- [ ] Browser Extension
- [ ] Other

**Comment by jinglescode** [comment]
@mackieq you have reference [example repo](https://github.com/MeshJS/examples/tree/main/next-app-route)?

**Comment by mackieq** [comment]
I created a project using the template npx meshjs my-app and found that the configuration file in this template lacks serverExternalPackages: ["@meshsdk/core", "@meshsdk/core-cst", "@meshsdk/react"], which caused the issue I mentioned above.
