### ISSUE TITLE
Keep inline datum in outgoing UTxO

### ISSUE THREAD

**Issue by workshop-maybe** [MeshJS/mesh#58]
Desired behavior: 
When building a smart contract transaction, a UTxO is spent from a Contract address, and a new UTxO is output to the same Contract address. The inline datum in the Output UTxO should be unchanged from input UTxO.

Current solution: 
I can use a GraphQL query to get the `datum.bytes` or the `datum.value` in an on-chain UTxO. The UTxO type in Mesh has an `output.plutusData` field where I can add the `datum.bytes` in the Input UTxO.

When building the transaction, I can use `sendValue` to send a UTxO back to the contract, where the "output" inline datum is included as the `Recipient.datum`. However, this requires the datum to be reconstructed in my TypeScript code. I could write a helper function that takes the `datum.value` from my GraphQL query, reformatting it as a Mesh `Data` object, but this seems inconvenient when the datum is already serialized on-chain.

Question / desired solution:
Is there currently a way that I can simply add the `datum.bytes` from my original query as inline datum to an output UTxO?

**Comment by abdelkrimdev** [comment]
I don't know if I'm able to understand your question 100%
but what you can do is: put the `UTxO` object you constructed previously using the GraphQL query. in `sendValue`.

`tx.sendValue(address, utxo)`

**Comment by workshop-maybe** [comment]
Good - yes, this is the approach I'd like to take. I'm currently getting a validation error with this approach but will try to figure out why
