### ISSUE TITLE
Error: getUsedCollateral not implemented..

### ISSUE THREAD

**Issue by adam-young-dev** [MeshJS/mesh#72]
Using AppWallet to send transaction to unlock assets as in [this example](https://meshjs.dev/apis/transaction/smart-contract).

Then get this error:

```
Error: [Transaction] An error occurred during build: Error: getUsedCollateral not implemented..
    at Object.build (/root/meshapp/node_modules/@martifylabs/mesh/dist/mesh.cjs:1:51612)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Same as [this topic in stackexchange](https://cardano.stackexchange.com/questions/9539/mesh-error-getusedcollateral-not-implemented).  Just put it here for reference.

**Comment by magicMax007** [comment]
I also encountered this problem, which made my project unable to continue.

**Comment by adam-young-dev** [comment]
I have to switch to Lucid. Not as user friendly as mesh but at least things can move forward.

**Comment by nft6666** [comment]
> I have to switch to Lucid. Not as user friendly as mesh but at least things can move forward.

I also tried to use Lucid, but I couldn't find a way to connect to the server wallet, can you tell me how to do it.

**Comment by adam-young-dev** [comment]
> I also tried to use Lucid, but I couldn't find a way to connect to the server wallet, can you tell me how to do it.

You mean browser wallet? Like Nami? Checkout this example: https://github.com/spacebudz/lucid/blob/da661d0635bb31e700370391de62d28987eae06a/src/examples/mint_simple_NFT.ts#L21

**Comment by jinglescode** [comment]
@nft6666 @adam-young-dev 

"Collateral" is something the light wallets (i.e. eternl, nami...) has as part of the wallet features. Thus using `browser wallet` component, you can get the collateral UTXOs "magically", and it will prompt error when its not set.

For `App wallet`, obviously it is very different purpose. You can literally build your own light wallet if you wish to.

For transactions with `app wallet`, the solution is as simple as `tx.setCollateral(utxo)`, where you pick the UTXO you want to use as the collateral.

**Comment by adam-young-dev** [comment]
@jinglescode 
Now I get a different error. Something about "...PPViewHashesDontMatch...". 
Can you provide a detail example of a working implementation of `app wallet` interacting with a smart contract?

**Comment by jinglescode** [comment]
Make sure you update to the latest version, as valentine's day patch changed the network's cost model.
