### ISSUE TITLE
Datum not shown in utxo

### ISSUE THREAD

**Issue by adam-young-dev** [MeshJS/mesh#75]
I send lovelace to an address with datum like:

```
  tx.sendLovelace(
    {
      address: 'addr_test1vq8ncnj4xszdpy2ew0fzh8mudkwywqyz4fv8fkqh3jn20lsfkxtvt',
      datum: {
        value: {
          alternative: 0,
          fields: [49]
        },
        inline: true
      },
    },
    '1111111'
  );
```

The datum shows in the utxo as expected.

But when there are multiple objects in the fields like `fields: [49,42]` or  `fields: [49,'ABC']` the transaction is sent but no datum in the utxo. Also, the `inline: true` doesn't seem to make any difference.

**Comment by abdelkrimdev** [comment]
Hi @adam-young-dev, can you please give the TX Hash of one of the transactions you submitted?

**Comment by adam-young-dev** [comment]
Just try it again. Same code. But it works now! [This transaction/datum](https://preprod.cexplorer.io/datum/0b6d83e4d37ac5aef99ce530ec1809355bda79aa39428fcda1f2f8eaaba88398).

This is very likely on my end. Sorry.
