### ISSUE TITLE
Typhon wallet is not working 

### ISSUE THREAD

**Issue by walifile** [MeshJS/mesh#82]
I'm trying to connect typhon wallet  its not work for me . 
Code I'm running :
`import { useWallet, useLovelace, CardanoWallet } from "@meshsdk/react";
 const { wallet, connected, name, connecting, connect, disconnect, error } = useWallet();
connect("typhoncip30");
`
Note : 
I'm using latest version of @meshsdk/react 

Error : 
![image](https://user-images.githubusercontent.com/89452621/210600030-5cc327ef-cf60-4c93-a124-bd0d4e784eee.png)

**Comment by jeremybarnes2342** [comment]
Hey @walifile try this instead: `connect("Typhon Wallet")`

**Comment by walifile** [comment]
Thanks @jeremybarnes2342 its work for me
