### ISSUE TITLE
Typhon Wallet not always detected

### ISSUE THREAD

**Issue by BenElferink** [MeshJS/mesh#84]
I have the latest version of Mesh.
It detects all my installed wallets with no problem, but Typhon isn't always detected.

I am not sure when it is detected, and when it isn't - it's random.

**Comment by jeremybarnes2342** [comment]
Also seeing this issue as well with Typhon wallet. If I refresh a few times... I'm unable to connect (enable) to Typhon. Like @belferink1996 said it's pretty random.

This seems to be a newish issue as well... this wasn't happening a week or so ago.
