### ISSUE TITLE
Issue with `enoughValueHasBeenSelected` function

### ISSUE THREAD

**Issue by jeremybarnes2342** [MeshJS/mesh#85]
I have a UTXO that looks like this:

![image](https://user-images.githubusercontent.com/120895543/212775066-9713a9d0-cb36-4313-8863-e16ee949294c.png)

The outputSet map I passed to the `largestFirstMultiAsset` looks like this:
```
const lovelaceMap = new Map();
lovelaceMap.set("lovelace", 4000000.toString())
```

When I run the `largestFirstMultiAsset` function it's returning only this 1 UTXO shown above... because the  `enoughValueHasBeenSelected` function is saying that there is enough value in it 

It's adding the lovelace unit quantity and the quantity of the asset there which has like 3999999999 etc (as shown above in the image). This is not correct though. 

I **DO NOT** have enough `lovelace` quantity (4000000) in this 1 UTXO (shown above)

Shouldn't this code block here in the `enoughValueHasBeenSelected` function only be reducing amounts that match the `asset.unit` variable - which in this case is `lovelace`? 

![image](https://user-images.githubusercontent.com/120895543/212775221-2dd6acd4-7f7e-4cc5-b4d0-69ca3f87abf9.png)

Doing something like this seems to return the correct amount of UTXO's (2 instead of 1) from the `largestFirstMultiAsset` function 

![image](https://user-images.githubusercontent.com/120895543/212775268-a6ad1c83-8916-4ffc-82f2-ab1b3f4aeb75.png)

**Comment by jeremybarnes2342** [comment]
Please let me know if my solution looks correct. I'd be happy to make a PR to make the fix :)

**Comment by abdelkrimdev** [comment]
Hi, @jeremybarnes2342 nice catch I missed this case somehow 😅 
your fix looks perfect if you can make a PR I would really appreciate it :)

**Comment by jeremybarnes2342** [comment]
> Hi, @jeremybarnes2342 nice catch I missed this case somehow 😅 your fix looks perfect if you can make a PR I would really appreciate it :)

Done! 👍
