### ISSUE TITLE
Reference documentation

### ISSUE THREAD

**Issue by nielstron** [MeshJS/mesh#98]
I had a look at mesh today and I *love* the guides. They are simple to understand workable examples.

Deviating from there is however close to impossible right now, because there is no way to inspect types apart from digging into the source code (manually!). Please set up some kind of reference, be it something auto-generated, just so that users can look up each type and definition without having to dig the source code for it.

**Comment by abdelkrimdev** [comment]
https://docs.meshjs.dev/
