### ISSUE TITLE
Error when following the Smart Contract guide

### ISSUE THREAD

**Issue by nielstron** [MeshJS/mesh#99]
I followed the Smart Contract guide here: https://meshjs.dev/guides/smart-contract

I have implemented everything exactly as described. Trying to  lock funds I get stuck with this error message in the console:
```
Uncaught (in promise) Deserialization failed in ScriptHash because: Invalid cbor: expected tuple 'hash length' of length 28 but got length Len(0)
```

**Comment by dchambers** [comment]
What was the solution please?
